name: balabanproje
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_database: ^12.0.0
  permission_handler: ^11.0.1

  socket_io_client: ^2.0.3+1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  rxdart: ^0.27.7
  stream_transform: ^2.1.0
  async: ^2.13.0
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  camera: ^0.10.5+9
  audioplayers: ^5.2.1
  just_audio: ^0.9.38
  path_provider: ^2.1.4
  flutter_webrtc: ^1.0.0
  shared_preferences: ^2.2.2
  firebase_storage: ^13.0.0
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/balabanproje-firebase-adminsdk-fbsvc-d4c62c5a8b.json
    - assets/sounds/