name: balabanproje
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  rxdart: ^0.27.7 # Stream birleştirme için
  stream_transform: ^2.1.0
  async: ^2.13.0
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/balabanproje-firebase-adminsdk-fbsvc-d4c62c5a8b.json