// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13Y6nGvZvxkLxvWSWJMENdMajfqxSoQU',
    appId: '1:914532151784:android:b45789ee77071fc565f45d',
    messagingSenderId: '914532151784',
    projectId: 'balabanproje',
    storageBucket: 'balabanproje.firebasestorage.app',
    databaseURL: 'https://balabanproje-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzEdkWegze0QsE4M7dVCXBL2SmfUkzdCY',
    appId: '1:914532151784:ios:63276dcfb6d2881265f45d',
    messagingSenderId: '914532151784',
    projectId: 'balabanproje',
    storageBucket: 'balabanproje.firebasestorage.app',
    iosBundleId: 'com.example.balabanproje',
    databaseURL: 'https://balabanproje-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAlKYTRaD_wDZlIiafc9Rv9aA2oK0sGo',
    appId: '1:914532151784:web:f9a030d8c7ae1a3c65f45d',
    messagingSenderId: '914532151784',
    projectId: 'balabanproje',
    authDomain: 'balabanproje.firebaseapp.com',
    storageBucket: 'balabanproje.appspot.com',
    measurementId: 'G-22M35XW0FV',
    databaseURL: 'https://balabanproje-default-rtdb.europe-west1.firebasedatabase.app',
  );
}